[gcp_service_account]
type = "service_account"
project_id = "apexnuera-chatbot-project"
private_key_id = "5919fb2c6bb3cd9f8c117feb788f6fe4b3c4efea"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQDIcnitpssFSnNd
WHEA7ykOXbzlb/HWRyRdYZ9+hriJkjLTD2vU+7+CRylD0QK2B20+3CO51VjDKH9T
UfydfgXFTVzh9Xw474nibskckGQA6bb56f2SM6xKK16bROjlIuZ7yEDcnzG58S4H
EXCdzjrsJACn98I3/CgZcnuZICMRqAQGk8anyA4CSmn14dJMxqry2y/TgrG82w/6
0bxsfqB0WXmatb99bJ+QI8Sm6xnIw8jYVemladKOHQ/eWtackjV7UUO3puqXbZgL
RYbLHrYxCq6DVsbZnbrshG+xkh79+bscDY3ANR6mK7EvFMEYef1D2jKc68Ebx34P
GjFgVEkpAgMBAAECggEAFo8ZiVOg/DSzlKEYQLZp3LnMgVbutQK3M0JCKMOBP8xi
J3JQHL2DgWZAXOdIQpPF5gHxDGBYN8iWQdqTj2cIP7sT9cNCyoac8kytGiee9aJY
CzrcJKjnnkZQxLFF88nQfkRclmfdORPNbhK2pa/43iw0HbNK2rGokqqZgfOFtt4K
fwa85ABek0/p8nSxQ9VRJPJqHCxj7Pzib4vYjiv5pSBihSx1ebWbmfPMM9GEuEP1
fjjOnHmh4TFxroROos9ui2cyrd5iD2sZmPAWzx75KKhKtLqYawL+iyFURiKWs7AH
oVgiViLqwuh/jjYbKjFXXMXTyz9Qy/qHLcj/ulPULQKBgQD2v4J10pNhrIMA907j
qC4xZ3FTeOmvdlop95LBU0+Mt09Ue0iMgcp92T4cH2XQF4oNEAsCInOS+IF8jHGc
I/qhClPXooXad745LhrLEYV+UygyjykwnHk++jf/7V9ELaFlItfX2A7WPBgCt7vA
Szr5Jgs+3xRqQCdTjP7nmwzBxQKBgQDP9ocKZrzJtZmwtNTNC104QfoxgfujSqYp
GP1ceNSQannkX1EQGGCrb13h80YQt6YnRJBlbqqbSjXBFZIsskrYQi1lGpW6lVLJ
GJ2nF59MwbHPfMVcf3BAI8MrH4wNWShDLuui/66CCUifJNToUm41dYS53OJMApDY
dJ3Bn+EUFQKBgFNS2ohVIsXiDp8d5HsGSQsP5noMo8VHzyzK2LkGHB/lqxlZRGeG
UM3stYejpqr9t/WvTDhdT+/6kSdw+dCDadhF94gi7taWhxsiEZQvh4fgJvvj0kID
JQJ6VrzK+Ne6HP1dJcxSvrfjtSv9xZ4rCXAnQ7boeCllHqKdQ1sMxeMNAoGAXvid
mQFsC83UHx+l4vHio3N196/9pAfONAyGf/lqUX1epw1kbq5DT2cvf6VihPXpehtU
ug28+ef8/m2EcMcHaRVnt7lZUXkp8k48iPc/t4TpV/EKDIDiWVg7o/DnO51QxsWh
tLGBFz94G71tQZ+LVvyRHXQjIEU3srIm7Sq/VjUCgYB+7639QG0Hkkcl7LS5o9k6
700A3iBho3DVFNgAJ4gNv8/zfBorjHPPV3RqfusfnpcteZ0fKm1T3j+Ce886LcJW
xyXD4DQUvaEZNIUw9XahBaicZFvUffs8xRaIMfOTL+3V8Ym1vlJz8uV/cnj/8akP
3zofJHEJZEya3FYjdjijwA==
-----END PRIVATE KEY-----"""
client_email = "apexnuera-service-bot@apexnuera-chatbot-project.iam.gserviceaccount.com"
client_id = "116805799899466963853"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/apexnuera-service-bot%40apexnuera-chatbot-project.iam.gserviceaccount.com"
